# Ejercicio 3

In [ ]:
#@title i
from scipy import stats
import random
import numpy as np
random.seed(42)
L = 2 * 0.001 # semiancho
cf = 0.95     # confianza
alfa = 1 - cf
# calculamos z_alpha/2 que cumple P(Z>z_alpha/2) = alpha/2
z_alfa_2 = stats.norm.ppf(1-alfa/2)
# calculamos el criterio de corte en base al semiancho y confianza
d = L / (2 * z_alfa_2)

def f(x):
  return np.sin(x) / x
# escaleo para llevar (pi,2pi)->(0,1)
def g(x):
  return f(np.pi * (1 + x)) * np.pi

############################################################################

media = g(random.random())
var, n = 0, 1
s = np.inf # desvio muestral
lista = []
while s > d:
  n += 1
  X = g(random.random())
  media_ant = media
  media = media_ant + (X - media_ant) / n
  var =  var * (1- 1 /(n-1)) + n*(media- media_ant)**2
  s = np.sqrt(var/n)
  if n in [1000,5000,7000]:
    lista.append(media)
    lista.append(s)
    lista.append((media - z_alfa_2 * s,media + z_alfa_2 * s))

lista.append(media)
lista.append(s)
lista.append((media - z_alfa_2 * s, media + z_alfa_2 * s))

print(f'Valor del corte (d) = {d},\nSimulaciones requeridas (n) = {n}')
print()
print('  #sim','|','  int  ','|','  s   ','|','  intervalo')
for i,j in zip([0,3,6,9],['  1000','  5000','  7000',n]):
  print(j,'|',f'{lista[i]:.4f}','|',f'{lista[i+1]:.4f}','|',f'({lista[i+2][0]:.4f},{lista[i+2][1]:.4f})')

Valor del corte (d) = 0.000510213456924654,
Simulaciones requeridas (n) = 170010

  #sim |   int   |   s    |   intervalo
  1000 | -0.4335 | 0.0067 | (-0.4466,-0.4205)
  5000 | -0.4375 | 0.0029 | (-0.4433,-0.4318)
  7000 | -0.4358 | 0.0025 | (-0.4407,-0.4309)
170010 | -0.4332 | 0.0005 | (-0.4342,-0.4322)


Integral calculada https://www.calculadora-de-integrales.com/#expr=sin%28x%29%20%2F%20x&lbound=%CF%80&ubound=2%CF%80

In [ ]:
#@title ii
from scipy import stats
import random
import numpy as np
random.seed(42)
L = 2 * 0.001 # semiancho
cf = 0.95     # confianza
alfa = 1 - cf
# calculamos z_alpha/2 que cumple P(Z>z_alpha/2) = alpha/2
z_alfa_2 = stats.norm.ppf(1-alfa/2)
# calculamos el criterio de corte en base al semiancho y confianza
d = L / (2 * z_alfa_2)

def f(x):
  return 3 / (3 + x**4)
# escaleo para llevar (0,infty)->(0,1)
def g(x):
  return f(1/x - 1) / x **2

############################################################################

media = g(random.random())
var, n = 0, 1
s = np.inf # desvio muestral
lista = []
while s > d:
  n += 1
  X = g(random.random())
  media_ant = media
  media = media_ant + (X - media_ant) / n
  var =  var * (1- 1 /(n-1)) + n*(media- media_ant)**2
  s = np.sqrt(var/n)
  if n in [1000,5000,7000]:
    lista.append(media)
    lista.append(s)
    lista.append((media - z_alfa_2 * s,media + z_alfa_2 * s))

lista.append(media)
lista.append(s)
lista.append((media - z_alfa_2 * s, media + z_alfa_2 * s))

print(f'Valor del corte (d) = {d},\nSimulaciones requeridas (n) = {n}')
print()
print('  #sim','|','  int  ','|','  s   ','|','  intervalo')
for i,j in zip([0,3,6,9],['  1000','  5000','  7000',n]):
  print(j,'|',f'{lista[i]:.4f}','|',f'{lista[i+1]:.4f}','|',f'({lista[i+2][0]:.4f},{lista[i+2][1]:.4f})')

Valor del corte (d) = 0.000510213456924654,
Simulaciones requeridas (n) = 3662136

  #sim |   int   |   s    |   intervalo
  1000 | 1.4786 | 0.0306 | (1.4185,1.5386)
  5000 | 1.4713 | 0.0138 | (1.4443,1.4984)
  7000 | 1.4701 | 0.0117 | (1.4472,1.4929)
3662136 | 1.4617 | 0.0005 | (1.4607,1.4627)


Integral calculada
https://www.calculadora-de-integrales.com/#expr=3%20%2F%20%283%2Bx%2A%2A4%29&lbound=0&ubound=inf

# Ejercicio 5

**a**

Si $P(M>n)$ significa que:
$$
U_1\leq U_2\leq\cdots\leq U_n
$$

Osea tenemos una lista $[U_1, U_2,\cdots, U_n]$ ordenada de menor a mayor. Como hay $n!$ posibles formas de permutar la lista significa y la lista ordenada es solo una de esas posibles permutaciones significa que la probabilidad de obtener la lista ordenada es $1/n!$ es decir:
$$
P(M>n)=\frac{1}{n!}
$$


**b**

Por a) y la expansion de taylor de $e^x$
$$
E[M] = \sum_{n=0}^{\infty} P(M > n)=\sum_{n=0}^{\infty}\frac{1}{n!}=\sum_{n=0}^{\infty}\frac{1^n}{n!}=e^1=e
$$

In [ ]:
#@title variable M
import random
def m_min():
  i = 1
  n_l = 0
  n_u = random.random()
  while n_l < n_u:
    i += 1
    n_l = n_u
    n_u = random.random()
  return i

Para estimar el valor de $e$ utilizamos la media muestral de la variable $M$ mediante simulaciones de `m_min`.

In [ ]:
#@title c
from scipy import stats
import random
import numpy as np
random.seed(20)

media = m_min()
var, n = 0, 1
var_m = np.inf

while var_m > 0.01:
  n += 1
  X = m_min()
  media_ant = media
  media = media_ant + (X - media_ant) / n
  var =  var * (1- 1 /(n-1)) + n*(media- media_ant)**2
  var_m = var/n

print(f'Simulaciones requeridas = {n}\n'
      f'      Varianza muestral = {var_m:.4f}\n\n'
      f'Valor estimado de e = {media:.5f}\n'
      f'     Error absoluto = {np.e-media:.5f}\n'
      f'     Error relativo = {(np.e-media)/np.e :.5f}\n'
)

Simulaciones requeridas = 64
      Varianza muestral = 0.0098

Valor estimado de e = 2.59375
     Error absoluto = 0.12453
     Error relativo = 0.04581



In [ ]:
#@title d
from scipy import stats
import random
import numpy as np
random.seed(20)
L = 0.1
cf = 0.95
alfa = 1 - cf
z_alfa_2 = stats.norm.ppf(1-alfa/2)
d = L / (2 * z_alfa_2)

media = m_min()
var, n = 0, 1
dev_m = np.inf

while dev_m > d:
  n += 1
  X = m_min()
  media_ant = media
  media = media_ant + (X - media_ant) / n
  var =  var * (1- 1 /(n-1)) + n*(media- media_ant)**2
  dev_m = np.sqrt(var/n)

print(f'    Valor del corte (d) = {d:.6f}\n'
      f'Simulaciones requeridas = {n}\n'
      f'        Desvio muestral = {dev_m :.5f}\n'
      f'              Intervalo = ({media - z_alfa_2 * dev_m:.3f},{media + z_alfa_2 * dev_m:.3f})\n\n'
      f'Valor estimado de e = {media :.6f}\n'
      f'     Error absoluto = {np.abs(np.e-media) :.5f}\n'
      f'     Error relativo = {np.abs((np.e-media)/np.e) :.5f}'
)

    Valor del corte (d) = 0.025511
Simulaciones requeridas = 1112
        Desvio muestral = 0.02551
              Intervalo = (2.662,2.762)

Valor estimado de e = 2.712230
     Error absoluto = 0.00605
     Error relativo = 0.00223


# Ejercicio 7

En este caso el estimador para analizar es la media muestral
$$
\hat\theta(X_1,\cdots,X_n)=\overline X(n)
$$

Dado que $a=-5,b=5$ queremos estimar:
$$
P(-5<\overline X(n)-\mu<5)=P(|\overline X(n)-\mu|<5)
$$

Hay $10$ datos $(x_1,\cdots,x_{10})$ por lo tanto $10^{10} = 1e10$ posibles muestras bootstrap, elegimos generar solo $N=1e5$. Como la media $\mu$ es desconocida tomamos una estimacion en base a la muestra dada $\mu\sim\hat\theta(x_1,\cdots,x_{10})$.



Entonces estimamos la probabilidad deseada generando $N$ muestras bootstrap de la forma $(x_{i_1}^{(j)},\cdots,x_{i_{10}}^{(j)})$ y luego contando:
$$
\frac{1}{N}\#\bigg\{(x_{i_1}^{(j)},\cdots,x_{i_{10}}^{(j)}),1\leq j\leq N:|\hat\theta(x_{i_1}^{(j)},\cdots,x_{i_{10}}^{(j)})-\mu|<5\bigg\}
$$

In [ ]:
import numpy as np
np.random.seed(42)
data = np.array([56, 101, 78, 67, 93, 87, 64, 72, 80, 69])
n = len(data)
# estimamos mu como la media muestral del sampleo original
mu = np.mean(data)
# elegimos la cantidad de muestras bootstrap a generar
n_bs = int(1e5)

count = 0
print('algunos sampleos de ejemplo')
for i in range(n_bs):
  # generamos una muestra bootstrap
  sample = np.random.choice(data, size=n)
  if i % 25000 == 0:
    print(f'{sample}')
  # vemos si la muestra generada cumple la propiedad
  if np.abs(np.mean(sample)-mu)<5:
    count += 1

print(f"\nEstimacion de p = {count/n_bs}")

algunos sampleos de ejemplo
[64 67 72 93 64 69 78 64 72 93]
[ 80  67  80  69  72  93  69  87  78 101]
[ 72  93 101  72  56 101  56  69  56  56]
[78 80 72 78 80 69 64 72 93 67]

Estimacion de p = 0.761
